<Project>
    <!-- 检查是否定义了 UsePackResourceTarget 属性 -->
    <PropertyGroup>
        <UsePackResourceTarget Condition="'$(UsePackResourceTarget)' == ''">false</UsePackResourceTarget>
    </PropertyGroup>

    <ItemGroup>
        <MyContentFiles Include="$(MSBuildProjectDirectory)\..\Content\**\*.*"/>
    </ItemGroup>

    <!-- 增量打包资源 -->
    <Target Name="PackResource"
            BeforeTargets="BeforeBuild"
            Condition="'$(UsePackResourceTarget)' == 'true'"
            Inputs="@(MyContentFiles)"
            Outputs="$(MSBuildProjectDirectory)\Content.zip">
        <PropertyGroup>
            <_CurDir>$(MSBuildProjectDirectory)\</_CurDir>
            <_ContentDir>$([System.IO.Path]::GetFullPath('$(_CurDir)..\Content').TrimEnd('\'))</_ContentDir>
        </PropertyGroup>

        <Message Text="[PackResource] 正在执行增量打包..." Importance="high"/>
        <ZipDirectory SourceDirectory="$(_ContentDir)" DestinationFile="$(_CurDir)Content.zip" Overwrite="true"/>
    </Target>

    <!-- 检查是否定义了 OutputFileName 属性 -->
    <PropertyGroup>
        <UsePackOutputTarget Condition="'$(OutputFileName)' == ''">false</UsePackOutputTarget>
    </PropertyGroup>

    <!-- 只有当 UsePackOutputTarget 为 true 时才导入目标 -->
    <Target Name="PackOutput" AfterTargets="Build" Condition="'$(UsePackOutputTarget)' == 'true'">
        <!-- 执行打包操作 -->
        <ZipDirectory SourceDirectory="$(OutputPath)" DestinationFile="$(OutputPath)/../$(OutputFileName)" Overwrite="true"/>
    </Target>

    <!-- 检查是否定义了 OutputApkName 属性 -->
    <PropertyGroup>
        <UseRenameApkTarget Condition="'$(OutputApkName)' == ''">false</UseRenameApkTarget>
    </PropertyGroup>

    <!-- 只有当 UseRenameApkTarget 为 true 时才导入目标 -->
    <Target Name="RenameApk" AfterTargets="Build" Condition="'$(UseRenameApkTarget)' == 'true'">
        <!-- 重命名 Apk -->
        <Copy SourceFiles="$([System.IO.Path]::GetFullPath('$(OutputPath)$(ApplicationId)-Signed.apk'))"
              DestinationFiles="$([System.IO.Path]::GetFullPath('$(OutputPath)..\$(OutputApkName)'))"/>
    </Target>
</Project>
