<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(GlobalTargetFramework)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Survivalcraft\Survivalcraft.csproj"/>
    </ItemGroup>
</Project>
