<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Engine</AssemblyName>
        <TargetFrameworks>$(GlobalTargetFramework);$(AndroidTargetFramework)</TargetFrameworks>
        <Platforms>AnyCPU</Platforms>
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)'=='$(GlobalTargetFramework)'">
        <DefineConstants>DESKTOP</DefineConstants>
        <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)'=='$(AndroidTargetFramework)'">
        <SupportedOSPlatformVersion>$(MinAndroidApiVersion)</SupportedOSPlatformVersion>
        <RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
        <DefineConstants>ANDROID</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <!-- Debug 配置 -->
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    </PropertyGroup>

    <!-- Release 配置 -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <Optimize>true</Optimize>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NAudio.Core" Version="2.2.1"/>
        <PackageReference Include="NAudio.Flac.Unknown" Version="1.0.4"/>
        <PackageReference Include="NLayer.NAudioSupport" Version="1.4.0"/>
        <PackageReference Include="NVorbis" Version="0.10.5"/>
        <PackageReference Include="Silk.NET.OpenAL" Version="2.23.0"/>
        <PackageReference Include="Silk.NET.OpenGLES" Version="2.23.0"/>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12"/>
        <PackageReference Include="Silk.NET.Input" Version="2.23.0"/>
        <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0"/>
        <PackageReference Include="Silk.NET.Windowing" Version="2.23.0"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='$(GlobalTargetFramework)'">
        <PackageReference Include="Silk.NET.OpenAL.Soft.Native" Version="1.23.1"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)'=='$(AndroidTargetFramework)'">
        <PackageReference Include="Silk.NET.SDL" Version="2.23.0"/>
        <PackageReference Include="Xamarin.AndroidX.Core" Version="1.17.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Reflection"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\Engine\Resources\Unlit.vsh" LogicalName="Engine.Resources.Unlit.vsh"/>
        <EmbeddedResource Include="..\Engine\Resources\Unlit.psh" LogicalName="Engine.Resources.Unlit.psh"/>
        <EmbeddedResource Include="..\Engine\Resources\Lit.psh" LogicalName="Engine.Resources.Lit.psh"/>
        <EmbeddedResource Include="..\Engine\Resources\Lit.vsh" LogicalName="Engine.Resources.Lit.vsh"/>
        <EmbeddedResource Include="..\Engine\Resources\DebugFont.lst" LogicalName="Engine.Resources.DebugFont.lst"/>
        <EmbeddedResource Include="..\Engine\Resources\DebugFont.png" LogicalName="Engine.Resources.DebugFont.png"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine.Core\Engine.Core.csproj"/>
        <ProjectReference Include="..\Engine.Serialization\Engine.Serialization.csproj"/>
    </ItemGroup>

</Project>
