<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(GlobalTargetFramework)</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
        <None Include="..\Content\Assets\Database.xml" Link="Fixtures\Database.xml"
              CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Content.Packaging\Content.Packaging.csproj"/>
        <ProjectReference Include="..\Survivalcraft\Survivalcraft.csproj"/>
        <ProjectReference Include="..\TerritoryStoneMod\TerritoryStoneMod.csproj"/>
    </ItemGroup>

</Project>
