<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Survivalcraft.ModTemplate</AssemblyName>
        <RootNamespace>Survivalcraft.ModTemplate</RootNamespace>
        <SurvivalcraftModId>example.mod</SurvivalcraftModId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SCNET.Survivalcraft"
                          Version="0.0.0.1"
                          ExcludeAssets="runtime"/>
        <PackageReference Include="SCNET.ContentTool"
                          Version="0.0.0.1"
                          PrivateAssets="all"/>
    </ItemGroup>
</Project>
