<Project Sdk="Microsoft.NET.Sdk" InitialTargets="PackResource">
    <PropertyGroup>
        <AssemblyName>Server</AssemblyName>
        <OutputType>Exe</OutputType>
        <Version>$(ScNetworkVersion)</Version>
        <TargetFrameworks>$(GlobalTargetFramework)</TargetFrameworks>
        <DefineConstants>$(DefineConstants);SERVER</DefineConstants>
        <Platforms>AnyCPU</Platforms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Game</RootNamespace>
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
    </PropertyGroup>

    <!-- Debug 配置 -->
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    </PropertyGroup>

    <!-- Release 配置 -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <Optimize>true</Optimize>
    </PropertyGroup>

    <PropertyGroup>
        <UsePackResourceTarget>true</UsePackResourceTarget>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Reflection"/>
        <Using Include="System.Diagnostics"/>
        <Using Include="Engine.Core"/>
        <Using Include="EntitySystem.Core"/>
        <Using Include="Game.Components"/>
        <Using Include="Game.Subsystems"/>
        <Using Include="Game.Utils"/>
        <Using Include="Game.Extensions"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Survivalcraft\Survivalcraft.csproj" SetTargetFramework="TargetFramework=net10.0">
            <AdditionalProperties>DefineConstants=DESKTOP;SERVER</AdditionalProperties>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <None Include="Content.scpak">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Import Project="..\SharedProperties\GlobalUsing.props"/>

</Project>
