<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(GlobalTargetFramework)</TargetFramework>
        <AssemblyName>VerificationBlockMod</AssemblyName>
        <RootNamespace>VerificationBlockMod</RootNamespace>
        <SurvivalcraftModId>verification.block</SurvivalcraftModId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SCNET.Survivalcraft"
                          Version="0.0.0.1"
                          ExcludeAssets="runtime"/>
        <PackageReference Include="SCNET.ContentTool"
                          Version="0.0.0.1"
                          PrivateAssets="all"/>
    </ItemGroup>
</Project>
