<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(GlobalTargetFramework)</TargetFramework>
        <AssemblyName>TerritoryStoneMod</AssemblyName>
        <RootNamespace>TerritoryStoneMod</RootNamespace>
        <SurvivalcraftModId>scnet.territory</SurvivalcraftModId>
        <SurvivalcraftContentTool>$(MSBuildThisFileDirectory)../ContentTool/bin/$(Configuration)/$(GlobalTargetFramework)/SCNET.ContentTool.dll</SurvivalcraftContentTool>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Survivalcraft\Survivalcraft.csproj" Private="false"/>
        <ProjectReference Include="..\ContentTool\ContentTool.csproj" ReferenceOutputAssembly="false"/>
        <EmbeddedResource Include="Resources\TerritoryDatabase.xml"/>
        <EmbeddedResource Include="Resources\BlocksData.txt"/>
        <EmbeddedResource Include="Resources\Lang\*.json" WithCulture="false"/>
    </ItemGroup>

    <Import Project="..\ContentTool\SCNET.ContentTool.targets"/>
</Project>
