<Project Sdk="Microsoft.NET.Sdk" InitialTargets="PackResource">

    <PropertyGroup>
        <AssemblyName>SurvivalcraftStarter</AssemblyName>
        <OutputType>WinExe</OutputType>
        <TargetFramework>$(GlobalTargetFramework)-windows</TargetFramework>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <UseWindowsForms>true</UseWindowsForms>
        <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <StartProgram>Starter</StartProgram>
    </PropertyGroup>

    <!-- Release 配置 -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <PublishSingleFile>true</PublishSingleFile>
        <OutputFileName>SCNET_Windows-$(Version).zip</OutputFileName>
        <UsePackOutputTarget>true</UsePackOutputTarget>
    </PropertyGroup>

    <!--声明需要打包资源-->
    <PropertyGroup>
        <UsePackResourceTarget>true</UsePackResourceTarget>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Content.zip">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\icon.png" LogicalName="Starter.Resources.icon.png"/>
    </ItemGroup>

    <ItemGroup>
        <!-- 这里的 TargetFramework, RuntimeIdendifier 必须硬编码，MSBuid 的限制，请勿修改 -->
        <ProjectReference Include="..\Survivalcraft\Survivalcraft.csproj" SetTargetFramework="TargetFramework=net10.0">
            <AdditionalProperties>RuntimeIdentifier=win-x64</AdditionalProperties>
        </ProjectReference>
    </ItemGroup>

</Project>
