<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(GlobalTargetFramework)</TargetFramework>
        <AssemblyName>SCNET.ContentTool</AssemblyName>
        <RootNamespace>Scnet.ContentTool</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Content.Packaging\Content.Packaging.csproj"/>
    </ItemGroup>
</Project>
