<Project Sdk="Microsoft.NET.Sdk" InitialTargets="PackResource">
    <PropertyGroup>
        <AssemblyName>ServerStarter</AssemblyName>
        <OutputType>Exe</OutputType>
        <Version>$(ScNetworkVersion)</Version>
        <TargetFramework>$(GlobalTargetFramework)</TargetFramework>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <StartProgram>Starter</StartProgram>
    </PropertyGroup>

    <!-- Release 配置 -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <PublishSingleFile>true</PublishSingleFile>
        <OutputFileName>SCNET_Server_Linux-$(Version).zip</OutputFileName>
        <UsePackOutputTarget>true</UsePackOutputTarget>
    </PropertyGroup>

    <PropertyGroup>
        <UsePackResourceTarget>true</UsePackResourceTarget>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Survivalcraft\Survivalcraft.csproj" SetTargetFramework="TargetFramework=net10.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="Content.zip">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <Import Project="..\SharedProperties\GlobalUsing.props"/>

</Project>
